---
- name: helm add repo
  shell: helm repo add {{ repo_name }} {{ url_repo_helm }}
  register: prometheus_add_repo

- name: helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: Instalando o Prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install
