- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repo'
    raw: 'apt-get update'
    changed_when: False
  - name: 'Instalando o Python'
    raw: 'apt-get install -y python3 && apt-get install -y python2.7'
    register: install_python
    changed_when: '"Setting up python" in install_python.stdout'
  roles:
  - { role: install_k8s, tags: ["install_k8s_role"]  } 
